" taglight.vim: Highligh tags generated by ctags.
" Author: Paul Meffle
" Version: 0.0.3
" License: MIT License

augroup Taglight
        autocmd!
        autocmd Syntax cpp call taglight#HighlightTags()
        autocmd BufWritePost *.cpp,*.hpp,*.h call taglight#HighlightTags()
augroup END
